### ISSUE TITLE
check out the ownCloud Notes API

### ISSUE THREAD

**Issue by jancborchardt** [litewrite/litewrite#184]
In an effort to support more widely used open protocols and software for syncing we should check out the ownCloud Notes API: https://github.com/owncloud/notes/wiki/API-0.2
Would especially be cool to support that because there are lots of ownCloud deployments already.

cc @jorin-vogel @Raydiation

**Comment by jorinvo** [comment]
Would be even nicer if owncloud could speak remotestorage directly...

Anyways I plan to change litewrite in a way to make it easy to switch the backend completely.
Then you could write another version embedded as owncloud app and without all the remotestorage.

**Comment by jancborchardt** [comment]
Yeah, remoteStorage + ownCloud was often discussed and tried but in short: it’s too difficult to run because of security reasons you need to serve the remoteStorage stuff from a separate origin. And at that point you might as well just run a dedicated remoteStorage server.

However ownCloud already speaks an open standard which is WebDAV. Notes are always in the /Notes subfolder. I think @PVince81 is working on a webdav js library for ownCloud at the moment (using the one of @evert?) which might be useful for us as well. @PVince81 any hints there?

Also cc @Henni @LukasReschke because they work on ownCloud Notes as well and might be interested. :) (With Litewrite it would be possible to have the Notes from ownCloud offline and cross-platform cause it’s an unhosted web app. E.g. Firefox OS users could then use it as an ownCloud Notes app.)

**Comment by skddc** [comment]
You don't get sync for free just by using WebDAV, though. Currently, it's rs.js that is making it an unhosted, offline-first app, because it does the caching and automatic sync for you. It's a non-trivial task to solve all the problems we solved in rs.js so far with custom app code.

> Yeah, remoteStorage + ownCloud was often discussed and tried but in short: it’s too difficult to run because of security reasons you need to serve the remoteStorage stuff from a separate origin. And at that point you might as well just run a dedicated remoteStorage server.

That's not really the case imo, and even if it is, the main benefit would still be re-using ownCloud user accounts and make them available via Webfinger/OAuth, in turn making it much easier to connect apps that store per-user data. The main problem in the past (afaik) was actually the Apache 304/CORS situation, which seems to be have been solved (at least in some browsers) since then.

**Comment by jorinvo** [comment]
I think we should add it independently from remoteStorage. This gives us more freedom and possibilities.
However, I recommend we get the app cleaned up and reorganized first before attempting to add more providers.

But ownCloud is definitely also on my personal list since I set up my own a few months ago =)
So, I'm happy for any help with the ownCloud syncing. Would be nice to have a js lib.
Last time I worked with the ownCloud API I had to write all the WebDAV code myself and it's not that fun.

**Comment by skddc** [comment]
> I think we should add it independently from remoteStorage. This gives us more freedom and possibilities.
> However, I recommend we get the app cleaned up and reorganized first before attempting to add more providers.

Definitely. Who knows, maybe the effort can result in a new sync abstraction where you can plug in both RS and ownCloud, as well as others. The RS connect is actually easy enough to do in app code alone (with a little help from a microlib maybe), and rs.js is not a requirement for clients, of course.

**Comment by jorinvo** [comment]
@skddc sounds like a good idea! Will look into this!

**Comment by jorinvo** [comment]
Let's stick with remotestorage for Litewrite.
If remotestorage and Owncloud/Nextcloud build a connection internally, would be nice.
Owncloud/Nextcloud users can user their own, integrated note-taking [app](https://apps.nextcloud.com/apps/notes) for now.
