### ISSUE TITLE
How to update to newer remotestorage.js

### ISSUE THREAD

**Issue by theWebalyst** [litewrite/litewrite#271]
I want to test a prototype remotestorage.js to which I'm adding a backend for connection to SAFE Network (http://safenetwork.org) but am struggling to understand what is required for litewrite.

From what I can see you are using the AMD version, so I'm building this and then replacing litewrite/lib/remotestorage.js with my remotestorage.amd.js

However, I'm getting an error "Uncaught ReferenceError: RemoteStorage is not defined" in remotestorage.js at this line.

```
  RemoteStorage.util = {
```

I see from your commits you made some local changes since remotestorage.js 0.12.1 but am struggling to figure out what I might need to do. I'm currently using RS.js master (0.12.2-pre). I tried making some manual changes to your litewrite/lib/remotestorage.js but failed miserably :-(

**If you have any suggestions for how I could take a current 0.12.2-pre version of remotestorage.amd.js and use it with litewrite please let me know.** It would be great to have litewrite as one of the early demo apps on SAFE Network!

**Comment by theWebalyst** [comment]
Ok, I see this has already been raised on the rs.js github:
https://github.com/remotestorage/remotestorage.js/issues/945

Hope you can help!

**Comment by jorinvo** [comment]
Unfortunately, we are using a modified version of remotestorage for litewrite at the moment.
Here you can see the modifications we did: https://github.com/litewrite/litewrite/commits/gh-pages/lib/remotestorage.js

It's basically the issue you pointed out already, @theWebalyst and also this issue here https://github.com/remotestorage/remotestorage.js/issues/917. Don't want to waste 60kb just for bluebird.

The thing with the remotestorage/remotestorage.js#945 issue is, that you have to go through the remotestorage library and find all the places it uses global variables.

If you'd like to experiment, the simplest solution would be to modify the remotestorage version we already bundle with litewrite instead (https://github.com/litewrite/litewrite/blob/gh-pages/lib/remotestorage.js).

Otherwise, I would wait for those remotestorage errors to get fixed.

**Comment by theWebalyst** [comment]
Thanks @jorinvo - I tried modifying your rs.js but might have another go now I have an idea what's needed.

**Comment by theWebalyst** [comment]
Update: not sure what I did before but I succeeded in patching your RS.js with my changes so can now test litewrite with SAFE Network... yay! Am very excited at the possibility of it being an early SAFE App - should give litewrite a lot of exposure too :-). Fingers crossed and thanks for your help.

**Comment by skddc** [comment]
I just opened a pull request that incorporates @jorinvo's patches into rs.js core. I could build from source and then use the AMD build in the latest Litewrite as is.

@jorinvo Would be cool if you could review that.
