### ISSUE TITLE
Question: how is content stored, and how can i make a backup of it to a thumbdrive?

### ISSUE THREAD

**Issue by ynoauun** [litewrite/litewrite#274]
Thanks

**Comment by jorinvo** [comment]
Hi @ynoauun, content is stored using [Remotestorage](https://remotestorage.io/).
Keeping the data secure is all up to the storage provider.
@skddc wrote a command line tool to make backups of your remotestorage: https://github.com/skddc/rs-backup
If you use litewrite without logging in, data is only stored in your browser in indexedDB. You could figure out a way to back it up but it probably won't be straight forward..

**Comment by theWebalyst** [comment]
@ynoauun possibly not of interest, but just in case, I'm working on extending RS.js to support storage on safenetwork.org (including making providing a version of litewrite which works with this) so that would be an effective form of backup. 

Neither my bit nor SAFEnetwork is ready yet, so something for the future! :smile:

**Comment by ynoauun** [comment]
Hey guys,

I'm really embarassed now, but I was doing some naughty stuff on my chromebook where I have litewrite installed as a chromeos app, and I forgot to use incognito for it. So I did a selective erase browser data operation just for the previous hour, and it seems to have erased all of my indexedDB-stored LW notes! There was so much stuff on there, I'm so mad!

Does anyone have any ideas about how I might be able to get my LW notes back? I was using them for absolutely everything!!!

Thanks a lot.

**Comment by skddc** [comment]
Very sorry to hear that! In general, you can't really trust local browser storage to keep your stuff, ever. The best idea is to use remoteStorage to sync your notes, so they're always safely backed up on a server.

Now, to get back your data, you could try to find the previous IndexedDB files in a system backup of yours. For Firefox, that would be something like `.mozilla/firefox/{profilename}/storage/default/https+++litewrite.net/idb/`. I'm not sure if it's easy to restore the data from those files; I've never done it myself.

**Comment by ynoauun** [comment]
Hi, @skddc thanks for the suggestion - I'm on ChromeOS, do you have any ideas about possible restoration methods for that? Thanks

**Comment by skddc** [comment]
Sorry, I'm not familiar with Chrome/ChromeOS in that regard. Maybe this helps: https://dev.chromium.org/user-experience/user-data-directory

However, I don't think ChromeOS even has system backups, because its selling point is that all data is always stored with Google. I may be wrong about that though.
