### ISSUE TITLE
Data Gone!

### ISSUE THREAD

**Issue by smwinters** [litewrite/litewrite#278]
Hi there! I've been using litewrite for about a year now, always on chrome and today I opened the page to find my writing gone and instead the "Welcome to Litewrite" blurb. Help please! Thanks!

**Comment by jorinvo** [comment]
@smwinters so sorry to hear this! 
Did you use remotestorage to synchronize your data or you just used litewrite in your browser?

**Comment by smwinters** [comment]
@jorinvo I'm not sure - how would I know? 

I used chrome

**Comment by jorinvo** [comment]
If you are not sure, you probably didn't use it.
It's the thing in the top right of the page. 
Without using remotestorage, all data you put in litewrite only stays in your web browser.
It's never sent to any service or backed up in any way. 
It's definitely not a way you want to keep anything important since the data the web browser saves can be reset in many ways without anyone having control over it.
There is little chance you can get any of the documents back, if your browser storage has been cleared.

One more thing you can try, in case the reason your data is gone is not that the browser cleared the storage but some kind of error occurred, then the data might be still saved in your browser.
You can try this:
- Open litewrite
- Right-click and click "Inspect"
- Open the tab "Console" in the developer tools that show up at the bottom
- Then you copy&paste the code below:
```js
indexedDB.open('remotestorage').onsuccess = function (e) {
	e.target.result.transaction("nodes").objectStore("nodes").getAll().onsuccess = function (e) {
		console.log(JSON.stringify(e.target.result))
	}
}
```
- Then press *enter*

What you get there is all your information stored in litewrite. You can see if there are some words in there you recognize. Otherwise can also copy it and send it to us to have a look.

**Comment by skddc** [comment]
The text should probably be adapted a little bit, because I think it wrongly suggests that brower storage is safe long-term, when really you should sync your stuff to a remote server:

> It works offline and your browser will keep your data saved (nerd facts: AppCache & localStorage).

By the way, we're already testing out rs.js 1.0 in actual apps (currently finishing up work on the new widget lib), and with that you can also easily connect Dropbox and Google Drive in addition to RemoteStorage accounts. I'll gladly help with upgrading this app.
