### ISSUE TITLE
RTL languages have a weird cursor movement

### ISSUE THREAD

**Issue by sudheesh001** [litewrite/litewrite#284]
I believe this is an enhancement request.

While typing arabic/urdu into the note, the user expects the cursor to move from the right towards the left. Instead the cursor stays on the left. It'd be nice to provide an option to choose between the LTR/RTL languages or possibly detect language and adjust accordingly?

### Current View
<img width="1440" alt="screen shot 2017-10-24 at 7 04 51 am" src="https://user-images.githubusercontent.com/4545925/31920938-da141832-b889-11e7-973b-2cd06910e76e.png">

### Expectation
<img width="1440" alt="screen shot 2017-10-24 at 7 05 42 am" src="https://user-images.githubusercontent.com/4545925/31920942-dcb4451c-b889-11e7-993f-1686063103db.png">

**Comment by jorinvo** [comment]
This is as simple as setting the CSS property `directtion: rtl;`. However the problem is detecting when the document is in an RTL language.
We already have a special case for cyrillic.
https://github.com/litewrite/litewrite/blob/fe7ebaa6337ffb641930320403d32cbf69fff4bb/src/views/editor.js#L58-L65

Similarly we could add an `rtl` CSS class. Only need to find out the regex to detect the right unicode blocks.

Pull Requests welcome :)

**Comment by jorinvo** [comment]
@sudheesh001 should be working on https://litewrite.github.io/litewrite/ now :)
