### ISSUE TITLE
Litewrite on Chrome Webstore

### ISSUE THREAD

**Issue by jancborchardt** [litewrite/litewrite#301]
We still have Litewrite on the Chrome Webstore, with a steady ~3500 weekly users:
https://chrome.google.com/webstore/detail/litewrite/cbdonnipllnmnkbmeopncohocjggmdkk

The issue is that it was last updated in August 2013 and will have some issues. It should be updated or removed – preferrably updated?

@jorinvo do you want to take over the Chrome Webstore app? Apparently there’s [a form](https://support.google.com/chrome_webstore/contact/dev_account_transfer) to transfer ownership of an app. (And considering you have done much more on Litewrite recently, and I also want to remove my Google account, it would make more sense for you to own it?) :slightly_smiling_face:

**Comment by jorinvo** [comment]
Hi, @jancborchardt! 
Unfortunately I also don't really work on Litewrite anymore apart from maintaining PRs. I'm still waiting for the day someone is exited about further developing Litewrite and I can pass along the role as maintainer 🙂  
But since you like to get rid of your Google account,  feel free to transfer the app to me. I will send you a DM on Twitter.
